### ISSUE TITLE
Hide categories!!

### ISSUE THREAD

**Issue by wuniversales** [realOxy/M3UAndroid#102]
**Is your feature request related to a problem? Please describe.**

I use a list to which I want to hide several categories and it is currently not possible to do so.

**Describe the solution you'd like**
Add an option to hide the list categories

**Describe alternatives you've considered**
I think it would be good to create an area only for the specific configuration of the lists and the configuration of the same (As I said earlier in my comment). 
https://github.com/realOxy/M3UAndroid/issues/56#issuecomment-1877724971

**Comment by realOxy** [comment]
Hide and pin playlist categories is available in latest commit. You can long press category tabs to invoke them.
