### ISSUE TITLE
VOD and Series Content Not Displayed

### ISSUE THREAD

**Issue by heberjeur** [realOxy/M3UAndroid#107]
**Describe the bug**
The M3U application does not display VOD and series content when accessing the respective screens. Instead, it shows nothing.

**To Reproduce**
1. Open the M3U application.
2. Navigate to the VOD or series section.
3. Click on the respective screen.
4. Observe that no content is displayed.

**Expected behavior**
I expected to see a list of available VOD and series content when accessing the respective screens within the M3U application.

**Screenshots**
![Screenshot_20240306-125544_M3U](https://github.com/realOxy/M3UAndroid/assets/11852634/938b8e11-5597-485a-bb49-56588640c5ee)

I currently have 2327 movies
![Screenshot_20240306-193142](https://github.com/realOxy/M3UAndroid/assets/11852634/0dbcd4d7-31de-4878-9ea0-7255ed3753ea)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A50
 - OS: Android 11
 - Version: [e.g. 2.0.1]

**Additional context**
This issue significantly impacts the usability of the M3U application, as it prevents users from accessing and enjoying VOD and series content. It would be greatly appreciated if this issue could be addressed and resolved in a future update.

**Comment by realOxy** [comment]
Can you provide the xtream url?

**Comment by realOxy** [comment]
Please try snapshot

**Comment by heberjeur** [comment]
> Please try snapshot

Hi @realOxy It works for VOD and not for series
![Screenshot_20240314-221037_M3U](https://github.com/realOxy/M3UAndroid/assets/11852634/485ae958-bb58-481e-bc2a-b927ccd13f1b)

**Comment by heberjeur** [comment]
It knows the number of my series but it's not displayed
![Screenshot_20240314-221435_Firefox](https://github.com/realOxy/M3UAndroid/assets/11852634/3383c6f4-e520-47d6-afaf-ca817a7e4eb4)

**Comment by heberjeur** [comment]
There are something wrong on number of links, I have those 

![Screenshot_20240314-222348](https://github.com/realOxy/M3UAndroid/assets/11852634/1c323b60-499c-4e9a-9d66-43daaf1fc44e)
![Screenshot_20240314-222332](https://github.com/realOxy/M3UAndroid/assets/11852634/8ba2eac3-bd3e-486f-88aa-52ce01490760)
![Screenshot_20240314-222312](https://github.com/realOxy/M3UAndroid/assets/11852634/d54a67b4-9ba6-4520-b29a-67122b4ca5fa)

**Comment by heberjeur** [comment]
> Can you provide the xtream url?

I send to your outlook mail my private account

**Comment by realOxy** [comment]
New beta package is out.
Now they can be displayed but I forgot test series with your link. 
The xtream json structure is so non-compliance that I must adjust my code.
Maybe I will solve it in 2 days.

**Comment by heberjeur** [comment]
Series error.., when I try to watch something

![Screenshot_20240316-230639_M3U](https://github.com/realOxy/M3UAndroid/assets/11852634/10fbb591-b02f-40b3-9d36-e2f3f69beba3)

**Comment by realOxy** [comment]
Try lastest snapshot apk
https://nightly.link/realOxy/M3UAndroid/workflows/android/master/artifact.zip

**Comment by heberjeur** [comment]
It works now !, live, series and vod.

**Comment by heberjeur** [comment]
I have incorrect streams numbers and incomplete lists 
![Screenshot_20240324-042724_M3U](https://github.com/realOxy/M3UAndroid/assets/11852634/285a15d2-6b09-48e7-8719-a3a7799d6ca2)

> There are something wrong on number of links, I have those
> 
> ![Screenshot_20240314-222348](https://private-user-images.githubusercontent.com/11852634/312999613-1c323b60-499c-4e9a-9d66-43daaf1fc44e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNTEzNTIsIm5iZiI6MTcxMTI1MTA1MiwicGF0aCI6Ii8xMTg1MjYzNC8zMTI5OTk2MTMtMWMzMjNiNjAtNDk5Yy00ZTlhLTlkNjYtNDNkYWFmMWZjNDRlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDAzMzA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTAwOGQ0MGY2Njg5ZTI2OWQ1ODA3N2EyMzk5N2EzN2IyNjRmZjE0NTE0MGNhNmZkMTI5MWM3ZWE4NWJkZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bmooRXvhXUuEZZz9lSGMUv5EyQFebhOOMc7P-J2ANNw) ![Screenshot_20240314-222332](https://private-user-images.githubusercontent.com/11852634/312999621-8ba2eac3-bd3e-486f-88aa-52ce01490760.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNTEzNTIsIm5iZiI6MTcxMTI1MTA1MiwicGF0aCI6Ii8xMTg1MjYzNC8zMTI5OTk2MjEtOGJhMmVhYzMtYmQzZS00ODZmLTg4YWEtNTJjZTAxNDkwNzYwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDAzMzA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NTZiYjJjYmFkMWM1MmM4OTFlMTEwOGYzOTVkNjYxY2MzYTY4NDIzODg3MmU2MTg1MDlkZDU0ZDU1ZjhlZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n75L94054WWDxN0Sb0qolb89hcg7AWpy_xC0oB_dqgg) ![Screenshot_20240314-222312](https://private-user-images.githubusercontent.com/11852634/312999630-d54a67b4-9ba6-4520-b29a-67122b4ca5fa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNTEzNTIsIm5iZiI6MTcxMTI1MTA1MiwicGF0aCI6Ii8xMTg1MjYzNC8zMTI5OTk2MzAtZDU0YTY3YjQtOWJhNi00NTIwLWIyOWEtNjcxMjJiNGNhNWZhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDAzMzA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZjljYTFlYzA0ZjhiM2YwNDAyNGRkNjY4YzVjZDcxZTdlNDM3YjVhZGE0MTU0ODE3YzQzYmM3NmFjZGU5MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DhzPP0pNyOTxgpUp-GpXp4g9d1CvwJ-SBb_sY3TR12c)

**Comment by realOxy** [comment]
This commit maybe helpful. Please wait the building is done and then try it. 
https://github.com/realOxy/M3UAndroid/commit/1d442ecec210a6638dde6e0209cff6c05b419f74
