### ISSUE TITLE
Double tap to title from context menu to select all

### ISSUE THREAD

**Issue by sguinetti** [realOxy/M3UAndroid#108]
**Is your feature request related to a problem? Please describe.**
It is a bit time consuming to have to hold down the text and then have to go to the "Select all" option to finally copy. The easiest way to copy the title of a channel or live stream is to use double tap (or clicks).

**Describe the solution you'd like**
Implement the double tap feature to select the whole name (or even copy) quickly.

**Describe alternatives you've considered**
It is a non-intrusive feature.

**Additional context**
This feature makes it easy to indicate the title for offline stream report to the provider along with the url of its stream. It also makes it easier to avoid typing the title when it is in another language.

**Comment by realOxy** [comment]
new bottom sheet will come out and the dialog will be deprecated (see roadmap in README).
so it will not be fixed.
