### ISSUE TITLE
How does this app work ?

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [realOxy/M3UAndroid#30]
How does this app work, how can you play m3u  streams?

**Comment by realOxy** [comment]
@mondlicht-und-sterne After installing, copy a playlist link, usually a link starting with http and ending with m3u or m3u8, open the software, settings, subscription management, parse the clipboard, and subscribe. Go back to the software homepage and you will see the playlist source you just imported.

#tutorial

**Comment by DarkCrypt** [comment]
How to add playlists:

Open app -> Settings -> Playlist Management.
- Playlist URL (m3u/m3u8).
A. Enter playlist name.
B. Enter playlist URL.
C. Subscribe.
D. Playlist saved on For You page.
- Playlist file (m3u/m3u8).
A. Toggle local storage switch.
B. Enter playlist name.
C. Select file from storage.
D. Subscribe.
E. Playlist saved on For You page.

How to watch:

Select playlist on For You page -> Select desired channel -> Player will open.
___
_Note_: Channels are categorized depending on playlist.

**Comment by DarkCrypt** [comment]
@realOxy 
I was also slightly confused the first time I used the app. The subscribe button threw me off. I think users will be expecting the button to say "+ Add Playlist" or something similar.
