### ISSUE TITLE
🐞[BUG]: Import File From Storage

### ISSUE THREAD

**Issue by DarkCrypt** [realOxy/M3UAndroid#31]
**Describe the bug**
After selecting m3u file from storage and hitting subscribe, notification says "check failed". Cannot import more than 101 streams and no streams will play.

**To Reproduce**
1. Import m3u file from storage.
2. See "check failed" notification in app.
3. Go to For You page.
4. Imports up to 101 channels only.
5. No streams work.

**Expected behavior**
Import file feature works correctly.

**Screenshots**
![Import_File_Check_Failed](https://github.com/realOxy/M3UAndroid/assets/121076677/8bfbd835-57ab-418b-b622-21d29e554351)
Check failed.

![Import_File_Incorrect_Channel_Count](https://github.com/realOxy/M3UAndroid/assets/121076677/4a89b8c4-2727-41ca-951c-48c31ad9db69)
Imports only up to 101 channels.

**Smartphone (please complete the following information):**
 - Device: OnePlus 9 Pro
 - OS: Android 13
 - App Version: 1.13.0

**Additional context**
This issue also affects the Settings page?

**Comment by realOxy** [comment]
@DarkCrypt Please provide this M3U file and I will try my best to find and solve this issue.

**Comment by DarkCrypt** [comment]
So far I've tried 2 different playlist files and 2 different playlist URLs. Iptv-org's URL is the only one which seems to work correctly.

Iptv-org
URL (self updating): https://iptv-org.github.io/iptv/countries/us.m3u
File: [Iptv-org_US.txt](https://github.com/realOxy/M3UAndroid/files/13509144/Iptv-org_US.txt)

Test
URL: https://epg.pw/test_channels_united_states.m3u
File: [test_channels_united_states.txt](https://github.com/realOxy/M3UAndroid/files/13509165/test_channels_united_states.txt)
___
_Note_: GitHub doesn't allow uploading m3u files within comments. Download the txt file and rename txt extension to m3u in order to use in player.

**Comment by DarkCrypt** [comment]
Still same issue as above comment, v1.13.1.

**Comment by realOxy** [comment]
You can try 1.13.2 version. Remember to disable settings -> experimental mode -> SSL certificate verification.

**Comment by DarkCrypt** [comment]
Disabling SSL certificate verification worked, v1.13.2. I can play the playlist now.
