### ISSUE TITLE
GitHub Releases Page Bug

### ISSUE THREAD

**Issue by DarkCrypt** [realOxy/M3UAndroid#34]
I've noticed within multiple repos that GitHub has been having issues displaying releases on the Releases page at times. The Tags page seems to work fine. After doing some investigating, I found a few old comments from the GitHub staff about this bug.

> On occasion, this can happen when the index used to populate the release page goes out of sync with the database holding release records.

> As an interim workaround, you can try editing the release and clicking on Update release without making any changes. This should force a re-sync, causing the missing releases to re-appear.

I reported this info to a different repo which had this same issue. The dev followed the instructions and the problem was solved.

You can try doing this for v1.13.1 since it's not showing on the Releases page.

**Comment by realOxy** [comment]
Thank you for your reminder. Although I didn't fully understand your meaning, as I could see version 1.13.1 on the release page, I checked the response from the GitHub Restful Release API and found that there was indeed no release information for 1.13.1. Afterward, I tried doing what you just mentioned, "clicking the Update release button," and it seems that the API response is now normal.

**Comment by DarkCrypt** [comment]
You could see v1.13.1 on Releases page before you clicked the "Update Release" button?

I see it on the Releases page now but only after you clicked the button. It wasn't there when I created this initial post. The reason I even noticed is because I use Obtainium to update apps.

To me this still seems like a sync issue as the GitHub staff said and by doing a force re-sync fixes it.

**Comment by realOxy** [comment]
@DarkCrypt Yees, 😂

**Comment by DarkCrypt** [comment]
Haha! Okie dokie, closing.
