### ISSUE TITLE
Zapping mode

### ISSUE THREAD

**Issue by sguinetti** [realOxy/M3UAndroid#36]
**Is your feature request related to a problem? Please describe.**
Greetings. It would seem great to improve the option to zap the streams (or lives) in the playlist, perhaps as an alternative to the experimental "scroll to change lives" feature. 

**Describe the solution you'd like**
For this feature, it would consist in pressing a button (or item from menu) to have the first stream previewed (in PIP). Then, the user will be able to tap the next channel and be previewed immediately (in PIP) until watching as many streams as possible.

**Describe alternatives you've considered**
This button would appear next to the update button. So it is not intrusive for the user.

**Additional context**
This feature is intended to save time by not having to watch the stream in full screen and not having to press the back button several times.

**Comment by realOxy** [comment]
@sguinetti Your ideas are interesting. I can add an option. When the user clicks to play any stream and jumps to the player, the PIP mode will be activated immediately. In addition, I can add a new button for switching streams in the player, and this feature and "gesture adjustment brightness and volume" will be merged into a "Player Optional Features" switch list.

**Comment by sguinetti** [comment]
Yes, you could have a section where the user can activate the optional features of the player. In that section you can add options like "Enable zapping mode", "Control brightness by gestures" and "Control sound by gestures". It also helps to implement accessibility options such as "Use subtitles", "Pause video when I'm calling", and so on. There are no limits to it.

**Comment by realOxy** [comment]
I have finished the implementation. What do you think is a better name for this feature in settings? My English is not good, so I haven’t decided yet.

**Comment by sguinetti** [comment]
In my humble opinion, "Zapping mode" is an name easy to remember. Under is a psychological reason, users can identify the feature to differentiate it from other applications that do not have this feature. So it is better to keep that name and thus have the app distinctive.

**Comment by sguinetti** [comment]
Anyway, thanks for accepting the proposal. In case you need help. Here are the new strings in spanish language for the file `i18n/src/main/res/values-es-rES/feat_setting.xml`

<string name="feat_setting_zap_mode">Modo zapeo</string>
<string name="feat_setting_zap_mode_description">Vista rápida de los directos antes de reproducirlos</string>

**Comment by sguinetti** [comment]
Perhaps you could consider the following feature for the future s an additional setting. To improve the Zapping mode, instead of displaying an error in the PIP window, it immediately goes to preview the next stream/live to save time.

**Comment by realOxy** [comment]
Now the status of stream (include title, subtitle, buttons or error) in player will not be shown when player is in PIP mode.

**Comment by sguinetti** [comment]
The feature works very well. So I will close this issue. Thank you.
