### ISSUE TITLE
4001 Player Error 

### ISSUE THREAD

**Issue by sguinetti** [realOxy/M3UAndroid#41]
**Describe the bug**
This error occurs in Zapping Mode, after watching several channels.

**To Reproduce**
1. Activate "Zapping Mode" and "display more information in the player" from settings
2. Add a list channel (m3u) like IPTVorg
3. Select first channel. After the first channel in floating window is streamed, then select the second channel, then select thrid channel, and so on.
4. Subsequently, only the logo will appear in the floating window (no the videostream, see screenshot).
5. The window must be opened in full screen.
6. The error is displayed below the channel name: "[4001] ERROR_CODE_DECODER_INIT_FAILED"

This error is best noticed when 10 channels that work without network problems are marked as favorites before zapping. After marking favorites, the step 4 is done. So it is ruled out that it is a problem of the m3u8 list.

**Expected behavior**
When viewing the window in full screen mode, the following warning will error "[4001] ERROR_CODE_DECODER_INIT_FAILED". The error appeared when I tuned to the Top Latino channel (per example) when I was checking at least 10 channels. After the error, when I select another channel, the 4001 error will remain until I close and reopen the app. 

**Screenshots**
![IMG_20231226_122048_457](https://github.com/realOxy/M3UAndroid/assets/5572928/06b1ba82-161b-4f4e-8418-7fa6b51da02e)

Illustration of the steps of the procedure (for easy follow-up).
![4001_report](https://github.com/realOxy/M3UAndroid/assets/5572928/4fb8aa54-4114-43f3-bea5-f75ba64fd455)

**Smartphone (please complete the following information):**
 - Device: Galay A04
 - OS: Android 13
 - Version 1.13.3 (app)

**Additional context**
I have tried this instructions in other smartphones with the same error. As far as I can tell it is a video player bug and not external.

In my opinion, I think the best solution to solve the problem is to have the player be initialized again, without the need to have to manually restart the app.

**Comment by realOxy** [comment]
You can try it in https://github.com/realOxy/M3UAndroid/commit/5d36946bdc299e4c62da793a5f86f967e7dc2c6a

**Comment by sguinetti** [comment]
Thank you.

**Comment by sguinetti** [comment]
Great. Since the stable version of the application was released, the app working without problem. I create a PR for add your app to [awesome-iptv](https://github.com/iptv-org/awesome-iptv) list: https://github.com/iptv-org/awesome-iptv/pull/208 I'm sure many viewers will be very happy.

**Comment by realOxy** [comment]
@sguinetti Thanks for your help.
