### ISSUE TITLE
Select quality of stream

### ISSUE THREAD

**Issue by sguinetti** [realOxy/M3UAndroid#43]
**Is your feature request related to a problem? Please describe.**
The option to choose the video quality, automatically or manually, is missing. Some live channels offer multiple resolutions and, for near-low connections (like 3G or congested networks), the feature is necessary to use the lowest possible videostream quality.

**Describe the solution you'd like**
There must be a button to select the resolution of the stream. It will be adapted according to the network connection.

**Describe alternatives you've considered**
The resolution selection will appear at the side of the list. See image for location. Another alternative is to place at the top next to other buttons.

In the future there will be other related technologies such as [ABR](https://www.linkedin.com/advice/3/what-emerging-trends-technologies-catch-up-time-shift-features). Anyway, it is always good to have a small big step.

**Additional context**
Concept: 
![Resolution_Concept](https://github.com/realOxy/M3UAndroid/assets/5572928/5a902d87-6250-4817-a0bc-1f441d51eb4c)

**Comment by realOxy** [comment]
I haven't seen an M3U that offers multiple video qualities, maybe you can provide me with one so I can develop and test it.

**Comment by wuniversales** [comment]
> I haven't seen an M3U that offers multiple video qualities, maybe you can provide me with one so I can develop and test it.

https://euronews-euronews-world-1-au.samsung.wurl.tv/manifest/playlist.m3u8

**Comment by sguinetti** [comment]
https://live.obslivestream.com/autenticatvmux/index.m3u8

**Comment by realOxy** [comment]
@sguinetti @wuniversales, I've made an initial commit regarding "stream quality." Additionally, a new feature, "compact mode," has been added as well. Where the styles of playlist and favorite screen items can be modified. While my intention was to transition all items to a compact style, I acknowledge that some individuals may prefer the previous style. Therefore, both options have been retained. Please give it a try and share your thoughts.

**Comment by sguinetti** [comment]
That's a good thing. It's very good to have a way to manage the way you view content. I would say that the application will have more customization than before.
