### ISSUE TITLE
One bug and two requests

### ISSUE THREAD

**Issue by VadosG** [realOxy/M3UAndroid#45]
Hey.
Great player.
I have something to report and suggest...

Bug: "Initial Screen" setting does not work
Request: Ability to start a specified channel at startup
Request: If possible - restart playback when hang-up occurs

Thanks.

**Comment by realOxy** [comment]
Thanks for your suggestions.
The "initial screen" bug will be fixed in the next version.
There are no plans to implement the ability to start playing at startup in the near future, but that doesn't mean it will never be available.
Additionally, a new feature called "auto-reconnect" will be included in the next version. It will always attempt to reconnect streams without displaying an error.

**Comment by realOxy** [comment]
https://github.com/realOxy/M3UAndroid/issues/44

**Comment by VadosG** [comment]
I use the player on a fairly limited Smart TV where you can't add custom shortcuts to the home screen, except for the application itself. That's why I suggested this functionality.

**Comment by realOxy** [comment]
Request: Ability to start a specified channel at startup

About this feature, I recommend you star target channel and set initial screen to favorite.

Other features and bugs have been solved.

Closed.

**Comment by VadosG** [comment]
Thank you for the changes made.
I didn't have a chance to report it before, I don't update the player on my Smart TV frequently, but starting with version 1.13.3 I started to have laggy playback. 4 seconds plays, 1 second pause, and it doesn't get any better. The most annoying thing is that it's only on Smart TV, on my smartphone I didn't have this problem before and after.

**Comment by realOxy** [comment]
@VadosG Are all channels playing like this?

**Comment by VadosG** [comment]
Hi. I have good news: starting from 1.14.0-beta03 video is no longer lagging.
Quick question: how to switch audio tracks if there is more than one?

**Comment by realOxy** [comment]
> Hi. I have good news: starting from 1.14.0-beta03 video is no longer lagging. Quick question: how to switch audio tracks if there is more than one?

In the latest snapshot version, you can switch tracks include video, audio, text.

You can get the snapshot package by clicking [this](https://nightly.link/realOxy/M3UAndroid/workflows/android/master/artifact.zip).

If it is not worked for you, please give me the playlist url and I will test it.

**Comment by VadosG** [comment]
I can't give a playlist, because it's IP bounded, but I took a video on my phone, the audio tracks don't change (same problem on TV too). 
I forgot to ask: on my Android TV there is a problem with accessing the file system to select the playlist file. The problem has been present since the beginning, and seems to be solved [here](https://github.com/moneytoo/Player/issues/248). It would be nice if you could add a different file access mode other than SAF. Thanks.

https://github.com/realOxy/M3UAndroid/assets/132702182/351804d7-5bdf-4f41-a1d4-9745669535c5

**Comment by realOxy** [comment]
For Android TV, there is a special subscription method. You can use your mobile phone side to assist TV side. You need to ensure that the latest version of the installation package is installed on the TV and mobile phone, then turn on their "remote control" switch, and then enter The pairing code appears on the TV. Finally, in the subscription management on the mobile phone, check the "for television" option to assist the TV subscription.
