### ISSUE TITLE
Share or save log file when app crashes

### ISSUE THREAD

**Issue by sguinetti** [realOxy/M3UAndroid#48]
**Is your feature request related to a problem? Please describe.**
It would be nice if the log files could be shared without the need to view the files. This option helps to include files when you want to report a bug.

**Describe the solution you'd like**
Add a menu to view, save or share the log file. Just tap and hold on a file. The feature will be applied in the "app crashes" screen.

**Describe alternatives you've considered**
I can find no other alternative. Besides, the option is not intrusive.

**Additional context**
This feature is useful for reporting a bug on Github and you need to attach a log file. This makes it easier to find a solution for an app crash.

**Comment by realOxy** [comment]
Now users can save logs as file.
