### ISSUE TITLE
Sort list alphabetically of favorites and ordinary channels

### ISSUE THREAD

**Issue by sguinetti** [realOxy/M3UAndroid#49]
**Is your feature request related to a problem? Please describe.**
This feature allows the user to sort the list alphabetically (a-z or z-a). This makes it easier for the user to locate the channel being searched for. Some lists offer the sorted list but when other lists are used, certain channels are not correctly located so that the user can easily find them.

**Describe the solution you'd like**
Sorting the channel list, especially from the favorites screen, helps a lot. This has a button (icon or text) to change the alphabetical order.

**Describe alternatives you've considered**
The button is displayed next to the section title.

**Additional context**
See screenshot:

![image](https://github.com/realOxy/M3UAndroid/assets/5572928/1a9cc10e-36a2-4e66-8cb6-6a00be5f731f)

In my opinion, in the channel list, the user can use the options to view all of the categories or a unified list sorted alphabetically (as if they were dictionary entries).

**Comment by realOxy** [comment]
In both the playlist and favorites screens, a new top bar button labeled 'Sort' will be added. Clicking this button will expand a sorting options bottom sheet, allowing users to select from 'Unspecified,' 'A-Z,' or 'Z-A' sorting modes. The 'Unspecified' mode corresponds to the default behavior for these lists.

https://github.com/realOxy/M3UAndroid/commit/7f2a9a284a058228f02688bc6feeb22bb95eb5f3

**Comment by realOxy** [comment]
<img width="782" alt="image" src="https://github.com/realOxy/M3UAndroid/assets/70512220/fa884e8d-dfc2-4f2f-ae6a-6619a76aaa19">

**Comment by sguinetti** [comment]
Good choice. These are subtle changes.
