### ISSUE TITLE
Integrate Xtream support into the M3U player

### ISSUE THREAD

**Issue by heberjeur** [realOxy/M3UAndroid#53]
**Is your feature request related to a problem? Please describe.**

The current lack of Xtream support in the M3U player limits users' choices and functionality, making it challenging to enjoy content through this platform.

**Describe the solution you'd like**

I propose the implementation of the Xtream feature in the M3U player, enabling users to access a broader range of channels and enhancing the overall streaming experience. This addition will provide users with more choices and make the app more versatile..

**Describe alternatives you've considered**

While there are various Xtream applications available, I prefer utilizing an open-source application like yours.

**Additional context**

**Comment by realOxy** [comment]
Could you tell me more about Xtream feature?

**Comment by sguinetti** [comment]
@realOxy I think it refers to Xtreme Codes. The feature is similar to m3u files but it stands out for being more personalized and private for customer users. It consists of a url server, with username and password for login.

I am not sure how the Xtreme Codes works because I have not seen the official source code of their servers (Xtream UI?). But, as far as I know, it falls back to APIs to deliver the m3u file. I only found documentation on the implementation in the IPTVnator app. https://github.com/4gray/iptvnator/issues/53

**Comment by realOxy** [comment]
@sguinetti Hi, where can I find a Xtream link for testing?

**Comment by sguinetti** [comment]
> @sguinetti Hi, where can I find a Xtream link for testing?

I find a public repository about this. But, I know about its content becuse I don't use Xtream links. 
https://github.com/m3u8-xtream/m3u8-xtream-playlist

**Comment by realOxy** [comment]
The app supports the Xtream from now on.
Currently, it will only get the live streams and they are not grouped by catalogs. 
I will add catalogs and other stream types(vod and series) supports.

**Comment by heberjeur** [comment]
@realOxy where I can add URL, user name and password like the screenshot, I can't found it.
![Screenshot_20240223-195552_Firefox](https://github.com/realOxy/M3UAndroid/assets/11852634/4c4746bd-9635-423a-b87f-c77ef5a5aff0)

**Comment by realOxy** [comment]
OK, I will add a down arrow icon here

**Comment by heberjeur** [comment]
There are something wrong, can you see this video:
https://we.tl/t-ANl2yBh3g5
If you want you can send to me a debug apk to known more about that...

**Comment by realOxy** [comment]
@heberjeur You didn’t send any video

**Comment by heberjeur** [comment]
> @heberjeur You didn’t send any video

https://we.tl/t-ANl2yBh3g5

**Comment by realOxy** [comment]
@heberjeur Please give me the xtream link, you can send it by https://t.me/sortBy

**Comment by themodfatherinc** [comment]
i am having trouble with this feature. when i input the name, host, username and password, and click subscribe i get the message that it is adding the task however the playlist is never added. do you have any ideas what could be the issue?

**Comment by themodfatherinc** [comment]
Ok I got this working, the Url parser seems to be forcing the xtream link to be http and i required https, changing the http to https in the function has everything working so it just needs to be changed to keep the scheme instead of default to http.
