### ISSUE TITLE
Pause (or mute) stream when the headphones are taken off

### ISSUE THREAD

**Issue by sguinetti** [realOxy/M3UAndroid#55]
**Is your feature request related to a problem? Please describe.**
In general, when people are in public places, they usually watch content with their headphones so as not to interrupt other people. For example, in public transportation or in a waiting line. In some reasons, the person forgets to turn down the volume (or pause the video) when disconnecting. The result is discomfort when the volume of the smartphone is high.

**Describe the solution you'd like**
The feature is missing. There should be an option to mute the audio in the player. It is also possible to pause the stream, although I'm not sure if this is appropriate for the app.

**Describe alternatives you've considered**
After muting the audio (or pausing the video) when the headphone is removed is not available in the app, there may be an option to replay. In case the "auto reconnect" feature is enabled, the stream would remain muted (or paused) until the user manually replay.

**Additional context**
Using the automatic function is quite useful in public places where you want to be as quiet as possible. As far as I have seen several apps with music playback control can also pause the content automatically.

**Comment by realOxy** [comment]
Now the player will mute the audio when it becoming noisy. For example, when a wired headset is unplugged, or when an A2DP audio sink is disconnected, and the audio system is about to automatically switch audio route to the speaker.
I have no headsets but only AirPods Pro. It works fine for me. You can test it in your devices.

**Comment by realOxy** [comment]
commits: 
https://github.com/realOxy/M3UAndroid/commit/a675933e1ba4415efaa7e2c98d84f2a4188d0b3a
https://github.com/realOxy/M3UAndroid/commit/49e6a27f0e758e300b264f229ed4b6adfbc4541a
https://github.com/realOxy/M3UAndroid/commit/c78c03148775fe2bbaa1d89ee5ab593c01d449aa

**Comment by realOxy** [comment]
I closed some issues which have been handled in release 1.13.5, I tested them in my devices and they are worked fine. If you find any other issue has not been resolved, you can reopen issues.
