### ISSUE TITLE
Delete and Edit Playlists

### ISSUE THREAD

**Issue by wuniversales** [realOxy/M3UAndroid#56]
**Is your feature request related to a problem?**

Yes, it's a big problem, I made a mistake when I put the address M3U8 and now I can't edit or delete it.

**Describe the solution you'd like**
Please make it possible to edit and delete lists from the configuration menu.

**Comment by sguinetti** [comment]
Playlists can be modified and removed from the main screen tapping for a second the list. Perhaps to avoid confusion, it would be better if the settings were clearer to understand.

@realOxy I know it's your application and you are able to define the user interface. But, to avoid possible misunderstandings such as this issue, I suggest a simple plus button to help users access the section to manage "playlists" directly with a easy section for adding. I have drawn a sketch for your reference, but you can design a better design as you prefer.

![image](https://github.com/realOxy/M3UAndroid/assets/5572928/314af386-ddbf-42c8-949f-308329ad0109)

**Comment by realOxy** [comment]
@sguinetti Maybe I can change the behavior of the "?" button, click it to navigate to settings -> playlist-management.
What do you think?

**Comment by sguinetti** [comment]
If it's simpler, then it is nice to change the behavior of the button to one with the "+" icon.  The "+" button would also appear next to the "m3u" text to access the playlist manager.

**Comment by wuniversales** [comment]
I like the @sguinetti idea.
I would add buttons to the right in each list (To improve compatibility with TV box, I tried to hold ok in the lists and I do not get the edit menu).

It would look like this:

List 1 [ Down arrow ( Down list ) ] [ Up arrow ( Up list ) ] [ Edit button ].

I think it would be good to put the delete button inside the edit button.
By the way, you can't edit the url!

Greetings

**Comment by realOxy** [comment]
@wuniversales The for-you screen ADD button will be added in next version.
The app currently does not fully support TV devices because jetpack's TV support for compose is not yet stable. After it is stable, I will try my best to optimize the software experience on TV devices.

**Comment by wuniversales** [comment]
I think it would be good to add an intermediate screen to manage the playlists, instead of going directly to add list.
That is, in "Playlist Management", list again all the current playlists, but adding the options to edit (Pencil icon) and move (With the arrows I said in my previous comment).
Then at the top right add the + button to add a new playlist.
