### ISSUE TITLE
Playlist management button disappears

### ISSUE THREAD

**Issue by wuniversales** [realOxy/M3UAndroid#57]
**Describe the bug**
The button simply seems to disappear from the configuration menu.

**To Reproduce**
- Enter configuration.
- Scroll to the bottom with the joystick.
- Scroll to the top with the joystick.
- The button has disappeared.

**Expected behavior**
That it works

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: TV Box x98 mini
 - OS: Android 11
 - Version: Latest Fdroid version

**Comment by realOxy** [comment]
Could you provide some screenshots?

**Comment by wuniversales** [comment]
It seems that with the latest version this bug has been fixed.
