### ISSUE TITLE
Larger buffering option

### ISSUE THREAD

**Issue by sguinetti** [realOxy/M3UAndroid#58]
**Is your feature request related to a problem? Please describe.**
In some cases, in high quality videos or in situations where users need to view content smoothly and without skips, the option of a "Larger buffering" will help to accomplish that need. For example, when the user wants to watch a full movie or listen to a video clip on the TV channel and you want to use an application to identify the origin of the music.

**Describe the solution you'd like**
Longer buffering is used in Adobe Flash Player to allow the content to be viewed in its entirety, especially if the connection has certain "skips" ("hiccups") that interrupt the experience. The Android app URL Radio also allows this option. Also PipePipe, opensource Youtube client, allows to increase the buffer to watch live streams.

**Describe alternatives you've considered**
This is an optional feature that is disabled. The user can enable it to correct "skips" in some streams, in return they need to load a little more to be able to watch them in full.

**Additional context**
It's a simple feature, no need to radically change the user interface.

**Comment by realOxy** [comment]
I don't know how to start 🙃

**Comment by sguinetti** [comment]
Well, I think Tunneling Mode might be an alternative to longer buffering. I'm not sure if it will be more efficient because it is focused on very high quality videos (I see from [Android docs](https://source.android.com/docs/devices/tv/multimedia-tunneling?hl=es)). I believe that tunneling mode, being a hardware technology, does not need a large buffer. I close for now, when necessary I will open this issue again.
