### ISSUE TITLE
Import and export all playlists and favorites

### ISSUE THREAD

**Issue by sguinetti** [realOxy/M3UAndroid#60]
**Is your feature request related to a problem? Please describe.**
Exporting and importing data locally is necessary for the user to keep their playlist and favorites. This can be useful for manually synchronizing or backing up to the user's cloud.

**Describe the solution you'd like**
The feature should be included in the application settings. If possible, manually added lists can be included in the file.

**Describe alternatives you've considered**
The feature is an alternative to keeping the information in case the user want to reset the app data and restore their backup. It is not intrusive. 

**Additional context**
Some applications such as NewPipe and AntenaPod include this function. The common format for backup is json.

If possible, it could be redesigned in a collapse menu that will allow the user to see the options. It is similar to "optional player features". 
![image](https://github.com/realOxy/M3UAndroid/assets/5572928/cc5a02c7-e3e6-4ed4-aea0-1c4f870f40be)

**Comment by realOxy** [comment]
Backing up and restoring data has been basically implemented. You can download the latest snapshot installation package or package it yourself for testing.

The current logic is simply to serialize all data into JSON and then write it to the file, so different APP versions of the data may be incompatible with each other.

**Comment by realOxy** [comment]
Get the latest SNAPSHOT package here:

https://nightly.link/realOxy/M3UAndroid/workflows/android/master/artifact.zip

**Comment by sguinetti** [comment]
Thank you for the announcements. I'm sorry to say that I can't use the snapshots because it is not yet able to install. Therefore, I can't test at the moment.

I think if you add the app version in the JSON file, so when importing from a different version of the backup, a warning would appear. Like this: "The backup you are importing was taken from a different version of the app than the one you are using now. Are you sure you want to import?"

**Comment by sguinetti** [comment]
@realOxy Hello again. I already have the Snapshot app, to be installed separately, and it is working fine for me. However, for that matter, the backup is somewhat limited. I have tried the pe.m3u playlist file [from iptv-org](https://github.com/iptv-org/iptv) and it only allows me to backup 195 out of 216 channels. Reviewing the file, the Uchu TV line is somewhat incomplete.
