### ISSUE TITLE
Crashing of app when non-stop scrolling favorite channels and pressing "For you" immediately

### ISSUE THREAD

**Issue by sguinetti** [realOxy/M3UAndroid#61]
**Describe the bug**
This bug occurs when scrolling through a list of several favorites while pressing "For you". The crash occurs when scrolling continues, as reproduced below.

**To Reproduce**
1. Importa a list of channels
2. Add a several favorites (like 15)
3. Unselect "No image" mode (optional but makes the bug more evident)
4. Start scrolling the list. To do this, the finger is pulled quickly from the bottom to the top.
5. Immediately, before it stops, "For you" is clicked.

![image](https://github.com/realOxy/M3UAndroid/assets/5572928/07c9be5f-8434-48c5-9ff3-7702bfca95ea)

**Expected behavior**
An error message appears. It goes directly to the "app crashes" screen. In some cases the app will remain in "For you" with no response. The app should be closed and reopened.

**Screenshots**
![image](https://github.com/realOxy/M3UAndroid/assets/5572928/e7a7ae86-372e-43c7-8b87-b978d1bcad32)

**Smartphone (please complete the following information):**
- Device: Galay A04
- OS: Android 13
- Version 1.13.5 (app)

This error is reproduced in the list of favorites only, regardless of whether "Compact mode" and "No image" are activated.

**Additional context**
Attached log:
[Crash report scroll favs.txt](https://github.com/realOxy/M3UAndroid/files/13847817/Crash.report.scroll.favs.txt)

**Comment by realOxy** [comment]
It seems to be jetpack compose mistake. It's hard to reproduce and I shouldn't be able to fix it.
Maybe just upgrade compose libraries and it will disappear in the future.

**Comment by sguinetti** [comment]
You are right. I try to reproduce this bug again in [1.14.0-alpha11](https://github.com/realOxy/M3UAndroid/releases/tag/v1.14.0-alpha11). Now it no longer crashes. Thank you, anyway. I will close.
