### ISSUE TITLE
Option to unfavorite and create shortcut from list of favorites

### ISSUE THREAD

**Issue by sguinetti** [realOxy/M3UAndroid#63]
**Is your feature request related to a problem? Please describe.**
A context menu to unfavorite and create a shortcut is missing in favorites list. It is a feature that simplifies the user experience.

**Describe the solution you'd like**
Just like a context menu in "For you", such as when marking favorites, the context menu should be extended as well.

**Describe alternatives you've considered**
I can find no other alternative. Since add a unfavorite option is more simple than manually searching from the "For you" screen.

**Additional context**
See screenshot:

![image](https://github.com/realOxy/M3UAndroid/assets/5572928/2e8df7e9-0e65-454b-82b3-4b2e905b1365)

**Comment by realOxy** [comment]
It will be available in the next version.
