### ISSUE TITLE
Problem with the search engine in tv box (With text fields in general)

### ISSUE THREAD

**Issue by wuniversales** [realOxy/M3UAndroid#67]
Currently with the text fields in the TV Box, the keyboard opens automatically when you hover over the text field, this is quite a big problem in the TV box because it does not allow me to scroll correctly to the next text field.
Although it is a general problem, the biggest problem is located in the hidden field of "Search" within the playlists, the search field in the tv box does not appear at any time, but scrolling with the arrows the tv box enters the hidden search field, the keyboard opens and does not let me continue scrolling correctly to the channels.

I propose not to open automatically the keyboard, only to open it by pressing "Ok" on the remote control.

**Comment by realOxy** [comment]
https://issuetracker.google.com/issues/316676796
