### ISSUE TITLE
"Search for this channel on Internet" from the context menu

### ISSUE THREAD

**Issue by sguinetti** [realOxy/M3UAndroid#70]
**Is your feature request related to a problem? Please describe.**
It is more practical to use the option "Search for this channel on Internet". This feature makes it easy to search the channel's website via web browser for more information about the channel's content. In addition, it also allows the user to search the social networks and interact beyond watching the TV channel.

For example, I want to search for "Euronews" on the Internet because its website is offering more information on a news item that, due to lack of time, only appears briefly in the channel's live headlines.

**Describe the solution you'd like**
Just add the option "Search this channel on Internet" and open in a default web browser. The query for search is the name of the channel. Also, the query will not include content in parentheses.

**Describe alternatives you've considered**
If possible, it should be opened in the browser with the default search engine. Otherwise, search engines such as Google, Startpage, Bing and Duckduckgo would be offered in the options.

**Additional context**
This feature is very useful when searching from the TV, as typing the channel title with the remote control takes longer than with a touch keyboard.

**Comment by sguinetti** [comment]
Update: Added visual concept.

![image](https://github.com/realOxy/M3UAndroid/assets/5572928/6e0b2944-58a8-4fe4-8d4e-14aaa22e5aa6)

**Comment by realOxy** [comment]
I'm not going to implement this feature because I think it's a non-essential feature

**Comment by sguinetti** [comment]
Hello, I personally see it as an essential feature because in addition to the example I gave, I find other reasons why I think it is necessary to use this feature ("quick search").
* Some channels may never have EPG, especially local channels from Latin America. Instead of having to type in the name of the channel, I prefer to search the Internet and see what content they offer from their website (their programming would be a bit sparse but I find it useful). 
* In some FAST channels, such as Pluto, they offer TV programs that, because they are new to older viewers, I find it difficult to understand their script and so I search on Wikipedia about the program in question. I find it useful if the program is for children that the channel itself cannot explain to me.
* When I watch an international channel and I am curious to understand if there is an English version, I have to search directly from a button. Then, I visit their website and use the automatic translator. This situation is frustrating for those who want to report a problem from the IPTVorg lists.
I hope these reasons are enough to implement such a feature. An alternative is to offer a button to copy the channel title and search from a web search engine or similar.
