### ISSUE TITLE
F-Droid (double) listing

### ISSUE THREAD

**Issue by IzzySoft** [realOxy/M3UAndroid#78]
First congrats for getting your app to F-Droid.org! My local scanner just reported its "double listing". At this point (and given a decent overlap of ~2 weeks), apps are usually removed from my repo. What is your stance of this? There are rare exceptions that can be made, if you say there are reasons why it should stay.

**Comment by realOxy** [comment]
@IzzySoft Hi, I just want to put this project on more channels so that more people can use this app.

**Comment by IzzySoft** [comment]
People using my repo usually also have F-Droid.org's repo active, so that's no reason :wink: Any other?

Btw, while here: the `featureGraphic.jpeg` in your fastlane has the wrong proportions. It should be either 1024x500 or 512x250 px. Also not sure if it will be found with the `.jpeg` extension, it's usually `.png` or `.jpg` (but that might be OK with F-Droid, you will find out then). Some improvements for your `full_description.txt`:

```html
<p><i>M3U</i> is a stream media player on Android devices. Android 8.0 and above supported.</p><p><br><b>Features:</b></p><ul><li>M3U and M3U8 files.</li><li>HTTPS and RTMP stream.</li><li>Android TV.</li></ul><p>More to come.</p>
```

And btw, no need to focus on the "free" – everything on F-Droid's and my repo is "free", so that's only stating the obvious (as is saying "for Android" :wink:)

**Comment by realOxy** [comment]
This is my college graduation project, I just hope it can be noticed by more people and earn more stars⭐️, there is no other reason🙃.
Thanks for your revision. I just copied the description of this repository on Github, so I didn't remove the word "FREE" initially.

**Comment by IzzySoft** [comment]
> I just hope it can be noticed by more people and earn more stars

As pointed out: Those using my repo with their F-Droid clients usually have the F-Droid repo enabled, too (very few disable it to only use my repo), so this is rather a "weak reason".

But given the rather decent size of your APK (my checker says ~7 MB), maybe we can make a compromise: I keep it for now, but set a reminder to check again in July (half a year from now). Should it then still remain well below 10 MB APK size, I shift the reminder for another half year. Once it exceeds that limit we re-evaluate what to do. Deal?

> Thanks for your revision. I just copied the description of this repository on Github, so I didn't remove the word "FREE" initially.

Gladly – and thanks for taking care!

**Comment by realOxy** [comment]
Deal

**Comment by IzzySoft** [comment]
Done: Marked for keep, reminder set for 2024-07-21.
