### ISSUE TITLE
About project - should not connect to Github

### ISSUE THREAD

**Issue by licaon-kter** [realOxy/M3UAndroid#79]
ref: https://github.com/realOxy/M3UAndroid/blob/32ab0c9d082534cfc2c6a3954a30cb6cfcb874f1/features/about/src/main/java/com/m3u/features/about/AboutViewModel.kt#L88

...it's just a bit of text, put it in the APK at build time

**Comment by realOxy** [comment]
> 
> 
> ref: https://github.com/realOxy/M3UAndroid/blob/32ab0c9d082534cfc2c6a3954a30cb6cfcb874f1/features/about/src/main/java/com/m3u/features/about/AboutViewModel.kt#L88
> 
> 
> 
> ...it's just a bit of text, put it in the APK at build time

You are right. I will rewrite the code
