### ISSUE TITLE
turn on or off closed captions/subtitles option

### ISSUE THREAD

**Issue by sguinetti** [realOxy/M3UAndroid#85]
**Is your feature request related to a problem? Please describe.**
On several channels I checked, some subtitles are enabled or disabled by default. So it would be appropriate to set an option to view or hide the subtitles.

The advantages of closed captions (which are usually presented subtitles) are usually several. In particular, it is in reading dialogues that would be difficult to understand by listening in a language (when the viewer is learning a language), so for reasons of accessibility.

Example: https://iptv-org.github.io/?q=nhk%20world ([m3u xjp-en stream](https://nhkwlive-xjp.akamaized.net/hls/live/2003458/nhkwlive-xjp-en/index.m3u8) and [bmcc-live es](https://cdn.nhkworld.jp/www11/nhkworld-tv/bmcc-live/es/playlist.m3u8)) 

**Describe the solution you'd like**
As with the resolution selection, the user may choose the language on a button in the player, when available. If it is not, the button simply does not appear.

**Describe alternatives you've considered**
To prevent multiple buttons from accumulating on the screen, the icons could be collapsed into a menu. This avoids overloading the user interface.

**Additional context**
See https://github.com/iptv-org/iptv/issues/6257

**Comment by realOxy** [comment]
The closed-captions are supported now.
You can choose it in player "Choose Format" bottom sheet. 
Now you can easy control different tracks in one bottom sheet.
Supports: video, audio and text tracks.
You can also select no track for any track type.

**Comment by sguinetti** [comment]
Thank you very much. I will try in Snapshot to see if it is able to perform various actions. I like what you have implemented: audio and video options in one button.
