### ISSUE TITLE
App crashes when opening tab Setting on Android 9

### ISSUE THREAD

**Issue by trungquangphan** [realOxy/M3UAndroid#86]
**Describe the bug**
Could not add new playlist or open Setting tab on Android 9
"Unknow error occurred" popup is shown when performing above actions

**To Reproduce**
1. Go to tab Setting OR
2. Click + button at tab For you

**Expected behavior**
All feature works normally

**Smartphone (please complete the following information):**
 - Device: [Galaxy S8]
 - OS: [Android 9]
 - Version [e.g. 1.14.0-alpha13]

**Additional context**
Here is the stack trace
[1706449843480.txt](https://github.com/realOxy/M3UAndroid/files/14076245/1706449843480.txt)

In the logcat when application get started, I also got the warning as below
[warning_when_app_started.txt](https://github.com/realOxy/M3UAndroid/files/14076246/warning_when_app_started.txt)

Note: This issue does not happen on Android OS 33

**Comment by realOxy** [comment]
Because I have made lots of refactoring and uncommitted changed today.
Please try this package:

https://docs.google.com/uc?export=download&id=1i_4CYGuPI1JDpiTum6GkOV-yNpLRAO3F

**Comment by trungquangphan** [comment]
Hi, the issue is still there.
[1706451471858.txt](https://github.com/realOxy/M3UAndroid/files/14076335/1706451471858.txt)

**Comment by realOxy** [comment]
I think it is a compose library bug, I created an [issue](https://issuetracker.google.com/issues/322625234) for it and set the default value to 0.dp temporary.
