### ISSUE TITLE
missing tooltip on player screen

### ISSUE THREAD

**Issue by rhjdvsgsgks** [realOxy/M3UAndroid#9]
i found that there is a "single select" button on the right upper corner of player screen. but i dont know what it means.  a tooltip is helpful in this kind of situation. which is missed now.

ps: seems like its a recording button. but not implemented yet. i just mistaken notion that it is a favorite button. it would be great to have a favorite button on the toolbar

**Comment by realOxy** [comment]
The latest release now includes the implementation. Join the [Telegram channel](https://t.me/m3u_android) to get it.
