### ISSUE TITLE
Option to edit playlist url

### ISSUE THREAD

**Issue by iboboc** [realOxy/M3UAndroid#98]
It will be helpful to have the option to edit the url of the playlist (currently you can edit only title).

Current options: Unsubscribe, Copy URL. Add new option Edit URL.

Additional feature request, from UI experience point of view: When you subscribe to a list, a toast message is displayed and it stay on the same screen. It makes more sense after subscribe to return to the home screen (For You/ Playlists screen).

Thanks.

**Comment by realOxy** [comment]
@iboboc I don't fully understand the additional feature request. Can you describe it in detail?
