### ISSUE TITLE
Cast stream to external devices

### ISSUE THREAD

**Issue by iboboc** [realOxy/M3UAndroid#99]
I am trying to use the casting experimental option (Screencast). On my device, currently, the scan does not stop and a limited/incomplete list is showed. 
![cast2](https://github.com/realOxy/M3UAndroid/assets/2733631/9f85f698-1819-4272-9e7d-174d3bc2c3d3)

Expectation is to detect all chromecast devices in the network, like other apps.
![cast1](https://github.com/realOxy/M3UAndroid/assets/2733631/4038b256-0cad-4158-a14f-15e0982450c0)

There are various resources available, but I assume there is a Google API or proprietary.
Eg.
VLC: https://github.com/videolan/vlc-3.0/tree/master/modules/stream_out/chromecast
Others: https://github.com/vitalidze/chromecast-java-api-v2 https://github.com/TeamNewPipe/PipeCast

**Comment by sguinetti** [comment]
I think a simple solution would be to use the "Open as..." button in the selected stream. Then one could open a video app that supports other forms of casting.

**Comment by realOxy** [comment]
@sguinetti Great idea. I have add it in the latest commit. You can visit it in cast bottom sheet.
